;;;; Emacs Bookmark Format Version 1;;;; -*- coding: utf-8-emacs; mode: lisp-data -*-
;;; This format is meant to be slightly human-readable;
;;; nevertheless, you probably don't want to edit it.
;;; -*- End Of Bookmark File Format Version Stamp -*-
(("org-capture-last-stored"
  (filename . "~/vaults/org/journals/2026-03-13.org")
  (front-context-string)
  (rear-context-string . "Daily Journal\n\n\n")
  (position . 132)
  (last-modified 27060 15579 95841 0))
)
