;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from config-options.el

(register-definition-prefixes "config-options" '("config"))


;;; Generated autoloads from data-size.el

(register-definition-prefixes "data-size" 'nil)


;;; Generated autoloads from filesystem-x.el

(register-definition-prefixes "filesystem-x" '("create-" "delete-file-and-buffer" "rename-file-and-buffer" "visit-emacs-"))


;;; Generated autoloads from leader-key-system.el

(autoload 'make-leader-menu "leader-key-system" "\
Create a keymap and general-define-key function for KEY.
Creates a keymap named `leader-NAME-map' and a `general-definer' macro
named `leader-NAME-menu'.

NOTE that this relies on there being a definer created called `leader-menu' as
the default.

BODY will be passed on to the definer macro, with the exception of these keys:

- `:PARENT' The definer that we want to wrap
- `:DISPLAY-NAME' The name displayed in which-key menus if not NAME.

(fn NAME KEY &rest BODY)" nil t)
(autoload 'add-leader-keys "leader-key-system" "\
This is like `make-leader-menu' but it does not create a definer or map.
NAME is the which-key name, KEY is key to bind, and BODY is the `general-def'
body.

- `:PARENT' The definer that we want to wrap
- `:DISPLAY-NAME' The name displayed in which-key menus if not NAME.

(fn NAME KEY &rest BODY)" nil t)
(register-definition-prefixes "leader-key-system" '("get-leader-menu-" "leader-menu-prefix-alist" "set-leader-menu-prefix"))


;;; Generated autoloads from os.el

(register-definition-prefixes "os" '("os-"))


;;; Generated autoloads from package-macros.el

(register-definition-prefixes "package-macros" '("use-"))


;;; Generated autoloads from package-metadata.el

(register-definition-prefixes "package-metadata" '("package-" "use-package-"))


;;; Generated autoloads from plist-x.el

(register-definition-prefixes "plist-x" '("plist-remove"))


;;; Generated autoloads from projectile-refactor.el

(register-definition-prefixes "projectile-refactor" '("projectile-"))


;;; Generated autoloads from config-keybindings.el

(autoload 'leader-key-menu-initialize "config-keybindings" "\
Create the top-level leader-key menu.")
(register-definition-prefixes "config-keybindings" '("config:emacs-leader-key-menu-list"))


;;; Generated autoloads from config-hook-functions.el

(autoload 'fundamental-mode-setup "config-hook-functions" "\
Define things that should be set in all modes.")
(autoload 'text-mode-setup "config-hook-functions" "\
Function to add commands to `text-mode-hook'.")
(autoload 'prog-mode-setup "config-hook-functions" "\
Function to add commands to `prog-mode-hook'.")
(autoload 'package-list-mode-setup "config-hook-functions" "\
Setup the package list buffer.")
(autoload 'json-mode-setup "config-hook-functions" "\
Setup the json mode.")
(register-definition-prefixes "config-hook-functions" '("before-save-setup"))


;;; Generated autoloads from use-config.el

(register-definition-prefixes "use-config" '("config:user-config-dir" "create-" "use-config"))

;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
